site_name: SHEBANQ
site_description: > 
  Saving Queries on the BHSA (Hebrew Bible + ETCBC linguistics)

site_url: "https://etcbs.github.io/shebanq/" 
site_author: Dirk Roorda

repo_name: etcbc/shebanq
repo_url: 'https://github.com/etcbc/shebanq/'

theme:
  name: material
  logo: images/shebanq_logo.png
  favicon: 'favicon.ico'
  development: false
  development_label: still in beta
  production_link: ''
  client:
    name: ETCBC
    url: http://www.etcbc.nl
    logo: images/etcbc_round.png 
  feature:
    tabs: true

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: etcbc
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - markdownextradata
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      watch:
        - "controllers"
        - "models"
        - "modules"
        - "ftests"
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path[0:0] = ["modules", "ftests", ".", "../../web2py/web2py"]
            - from gluon.cache import Cache
            - cache = Cache({})
            - print(cache)
          selection:
            docstring_style: numpy
          rendering:
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true
            members_order: source
  - minify:
      minify_html: true

extra:
  # App
  repoName: shebanq
  repoUrl: https://github.com/etcbc/shebanq
  repBase: https://github.com/etcbc/shebanq/blob/master
  liveBase: https://shebanq.ancient-data.org
  repo: https://github.com/etcbc/shebanq
  wiki: https://github.com/ETCBC/shebanq/wiki
  docSite: https://etcbc.github.io/shebanq

  # Rest
  apache: https://httpd.apache.org
  appleCmd: https://developer.apple.com/library/archive/technotes/tn2339/_index.html 
  appleCmdDoc: https://developer.apple.com/library/archive/documentation/OpenSource/Conceptual/ShellScripting/CommandLInePrimer/CommandLine.html
  appleCmdInstall: https://www.freecodecamp.org/news/install-xcode-command-line-tools/
  atom: https://atom.io 
  bash: https://www.gnu.org/software/bash/
  bhsa: https://github.com/etcbc/bhsa
  black: https://black.readthedocs.io/en/stable/
  bol: https://bibleol.3bmoodle.dk/text/show_text/ETCBC4/Genesis/1
  css: https://developer.mozilla.org/en-US/docs/Web/CSS
  dans: https://dans.knaw.nl
  emdros: https://emdros.org
  eslint: http://eslint.org
  etcbc: http://www.etcbc.nl
  fancytree: https://github.com/mar10/fancytree/
  flake8: https://github.com/PyCQA/flake8
  githubBase: https://github.com/
  homebrew: https://brew.sh
  html: https://developer.mozilla.org/en-US/docs/Web/HTML
  javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript
  jquery: https://api.jquery.com
  mariadb: https://mariadb.org
  markdownDoc: https://guides.github.com/features/mastering-markdown/
  mkdocs: https://github.com/mkdocs/mkdocs
  mkdocsmaterial: https://github.com/squidfunk/mkdocs-material
  mysql: https://dev.mysql.com/downloads/mysql/
  mysqlInstall: https://dev.mysql.com/doc/mysql-macos-excerpt/8.0/en/macos-installation-pkg.html
  parabible: https://parabible.com/Genesis/1
  pdoc3: https://pdoc3.github.io/pdoc/
  pipeline: https://github.com/etcbc/pipeline
  pytest: https://github.com/pytest-dev/pytest
  pytestFixtures: https://docs.pytest.org/en/latest/explanation/fixtures.html
  python: https://www.python.org
  pythondocstrings: https://www.python.org/dev/peps/pep-0257/
  pythonLogging: https://docs.python.org/3/library/logging.html#module-logging
  scp: https://man.openbsd.org/scp.1
  selenium: https://www.selenium.dev
  selinux: https://en.wikipedia.org/wiki/Security-Enhanced_Linux
  shellsudo: https://linuxtect.com/linux-sudo-command-run-commands-with-root-privileges/
  ssh: https://man.openbsd.org/ssh.1
  ssl: https://smallstep.com/blog/use-ssh-certificates/
  textfabric: https://annotation/text-fabric
  web2py: http://web2py.com
  web2pyRepo: https://github.com/web2py/web2py
  web2pyCache: http://web2py.com/books/default/chapter/29/04/the-core#cache
  web2pyComponents: http://www.web2py.com/books/default/chapter/29/12/components-and-plugins#Components-LOAD-and-Ajax
  web2pyCurrent: http://web2py.com/books/default/chapter/29/04/the-core#Sharing-the-global-scope-with-modules-using-the-current-object
  web2pyLogging: http://web2py.com/books/default/chapter/29/04/the-core#Logging
  webApi: https://developer.mozilla.org/en-US/docs/Web/API/document
  wsgi: https://modwsgi.readthedocs.io/en/develop
  yaml: http://www.yaml.org
  zenodo: https://zenodo.org
